Controllers/AboutController.cs
using MyDatabase;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.ClassCommon;

namespace WebAppMVC.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        private MyDB db = new MyDB();
        #region Cong Ty Thien Phong
        private const int CREATE_NEW = 1;
        private const int OPEN_EXISTING = 3;
        private const uint GENERIC_READ = 0x80000000;
        private const uint GENERIC_WRITE = 0x40000000;
        private const int FILE_SHARE_READ = 0x1;
        private const int FILE_SHARE_WRITE = 0x2;
        private const int VER_PLATFORM_WIN32_NT = 2;
        private const int DFP_RECEIVE_DRIVE_DATA = 0x7C088;
        private const int INVALID_HANDLE_VALUE = -1;

        [StructLayout(LayoutKind.Sequential, Size = 8)]
        private class IDEREGS
        {
            public byte Features;
            public byte SectorCount;
            public byte SectorNumber;
            public byte CylinderLow;
            public byte CylinderHigh;
            public byte DriveHead;
            public byte Command;
            public byte Reserved;
        }

        [StructLayout(LayoutKind.Sequential, Size = 32)]
        private class SENDCMDINPARAMS
        {
            public int BufferSize;
            public IDEREGS DriveRegs;
            public byte DriveNumber;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public byte[] Reserved;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public int[] Reserved2;
            public SENDCMDINPARAMS()
            {
                DriveRegs = new IDEREGS();
                Reserved = new byte[3];
                Reserved2 = new int[4];
            }
        }
        [StructLayout(LayoutKind.Sequential, Size = 12)]
        private class DRIVERSTATUS
        {
            public byte DriveError;
            public byte IDEStatus;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public byte[] Reserved;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public int[] Reserved2;
            public DRIVERSTATUS()
            {
                Reserved = new byte[2];
                Reserved2 = new int[2];
            }
        }

        [StructLayout(LayoutKind.Sequential)]
        private class IDSECTOR
        {
            public short GenConfig;
            public short NumberCylinders;
            public short Reserved;
            public short NumberHeads;
            public short BytesPerTrack;
            public short BytesPerSector;
            public short SectorsPerTrack;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public short[] VendorUnique;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public char[] SerialNumber;
            public short BufferClass;
            public short BufferSize;
            public short ECCSize;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
            public char[] FirmwareRevision;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 40)]
            public char[] ModelNumber;
            public short MoreVendorUnique;
            public short DoubleWordIO;
            public short Capabilities;
            public short Reserved1;
            public short PIOTiming;
            public short DMATiming;
            public short BS;
            public short NumberCurrentCyls;
            public short NumberCurrentHeads;
            public short NumberCurrentSectorsPerTrack;
            public int CurrentSectorCapacity;
            public short MultipleSectorCapacity;
            public short MultipleSectorStuff;
            public int TotalAddressableSectors;
            public short SingleWordDMA;
            public short MultiWordDMA;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 382)]
            public byte[] Reserved2;
            public IDSECTOR()
            {
                VendorUnique = new short[3];
                Reserved2 = new byte[382];
                FirmwareRevision = new char[8];
                SerialNumber = new char[20];
                ModelNumber = new char[40];
            }
        }

        [StructLayout(LayoutKind.Sequential)]
        private class SENDCMDOUTPARAMS
        {
            public int BufferSize;
            public DRIVERSTATUS Status;
            public IDSECTOR IDS;
            public SENDCMDOUTPARAMS()
            {
                Status = new DRIVERSTATUS();
                IDS = new IDSECTOR();
            }
        }

        [System.Runtime.InteropServices.DllImport("kernel32.dll")]
        private static extern int CloseHandle(int hObject);

        [System.Runtime.InteropServices.DllImport("kernel32.dll")]
        private static extern int CreateFile(
                    string lpFileName,
                    uint dwDesiredAccess,
                    int dwShareMode,
                    int lpSecurityAttributes,
                    int dwCreationDisposition,
                    int dwFlagsAndAttributes,
                    int hTemplateFile
                );

        [System.Runtime.InteropServices.DllImport("kernel32.dll")]
        private static extern int DeviceIoControl(
                int hDevice,
                int dwIoControlCode,
                [In(), Out()] SENDCMDINPARAMS lpInBuffer,
                int lpInBufferSize,
                [In(), Out()] SENDCMDOUTPARAMS lpOutBuffer,
                int lpOutBufferSize,
                ref int lpBytesReturned,
                int lpOverlapped
            );

        private string SwapChars(char[] chars)
        {
            for (int i = 0; i <= chars.Length - 2; i += 2)
            {
                char t;
                t = chars[i];
                chars[i] = chars[i + 1];
                chars[i + 1] = t;
            }
            string s = new string(chars);
            return s;
        }

        #endregion

        public string masohdd = "";
        public ActionResult Index()
        {
            if (Session["user_id"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Users");
            }
        }
        public ActionResult GetBanQuyen()
        {
            try
            {
                var congty_id = Convert.ToInt32(System.Web.HttpContext.Current.Session[CommonConstants.CONGTY_SESSION]);
                
                var items = db.DmCongTyCF.Where(x => x.CongTy_ID == 1).FirstOrDefault();

                var TenCty = items.TenCongTy;
                var Address = items.DiaChi;
                var DateCap = ThienPhong.Decrypt(items.MS01, "hientai@2018@cungtroi");
                var DateHetHan = ThienPhong.Decrypt(items.MS02, "thien@04120110@cungtroi");
                return Json(new { TenCty, Address, DateCap, DateHetHan }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

Controllers/DmBanController.cs
using MyDatabase;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.ClassCommon;

namespace WebAppMVC.Controllers
{
    public class DmBanController : Controller
    {
        // GET: DmBan
        private MyDB db = new MyDB();
     
        [CustomAuthorizeAttribute(RoleID = "FrmDmBan", QuyenXem = true)]
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetListDmBan()
        {
            var id = Convert.ToInt32(System.Web.HttpContext.Current.Session[CommonConstants.CONGTY_SESSION]);
            var list = db.DmBanCF.Where(x => x.TenCongTy_ID == id).ToList();

            //return Json(modefiedData, JsonRequestBehavior.AllowGet);
            return Json(new { data = list }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Create(DmBanCF dmBanCF)
        {
            //check the same code 
            var congty_id = Convert.ToInt32(System.Web.HttpContext.Current.Session[CommonConstants.CONGTY_SESSION]);
            var validateName = db.DmBanCF.FirstOrDefault(x => x.TenBan == dmBanCF.TenBan && x.TenCongTy_ID == congty_id);
            if (validateName != null)
            {
                //khac null la đúng điều kiện =
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                bool isSuccess = true;
                try
                {
                    db.DmBanCF.Add(dmBanCF);
                    db.SaveChanges();
                }
                catch (Exception)
                {
                    isSuccess = false;
                }
                return Json(isSuccess, JsonRequestBehavior.AllowGet);
            }
        }
        //[CustomAuthorizeEdit(RoleID = "FrmDmBan", QuyenSua = true)]
        public ActionResult Edit(long? id)
        {
            var data = db.DmBanCF.FirstOrDefault(x => x.Ban_ID == id);

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult CheckIdAndName(long id, string name)
        {
            var IdAndName = db.DmBanCF.FirstOrDefault(x => x.Ban_ID == id && x.TenBan == name);
            if (IdAndName != null) //đủ điều kiện
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult SaveEdit(DmBanCF dmBanCF)
        {
            //update tung truong
            var row = db.DmBanCF.FirstOrDefault(x => x.Ban_ID == dmBanCF.Ban_ID);
            row.TenBan= dmBanCF.TenBan;
            row.GiaBan = dmBanCF.GiaBan;
            db.Entry(row).State = EntityState.Modified;
            db.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        public JsonResult CheckNameAndCongTy(string name)
        {
            var id = Convert.ToInt32(System.Web.HttpContext.Current.Session[CommonConstants.CONGTY_SESSION]);
            var Name = db.DmBanCF.FirstOrDefault(x => x.TenBan == name && x.TenCongTy_ID == id);
            if (Name != null) //đủ điều kiện
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult Delete(long id)
        {

            //kiem tra id co ton tai trong phieu
            var Ph = db.Ph_XuatCF.Where(x => x.Ban_ID == id).FirstOrDefault();
            if (Ph != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var myID = db.DmBanCF.Where(x => x.Ban_ID == id).FirstOrDefault();
                db.DmBanCF.Remove(myID);
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }
        //kiem tra quyen tao phieu

        public ActionResult CheckQuyenCreate()
        {
            string UserId = Convert.ToString(System.Web.HttpContext.Current.Session[CommonConstants.USER_SESSION]);
            var validateName = db.AccessRightCF.Count(x => x.QuyenID == "FrmDmBan" && x.TaiKhoan == UserId && x.Tao == true);
            if (validateName == 1)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult CheckQuyenEdit()
        {
            string UserId = Convert.ToString(System.Web.HttpContext.Current.Session[CommonConstants.USER_SESSION]);
            var validateName = db.AccessRightCF.Count(x => x.QuyenID == "FrmDmBan" && x.TaiKhoan == UserId && x.Sua == true);
            if (validateName == 1)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult CheckQuyenDelete()
        {
            string UserId = Convert.ToString(System.Web.HttpContext.Current.Session[CommonConstants.USER_SESSION]);
            var validateName = db.AccessRightCF.Count(x => x.QuyenID == "FrmDmBan" && x.TaiKhoan == UserId && x.Xoa == true);
            if (validateName == 1)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult UpdateStatus(long id)
        {
            var row = db.DmBanCF.Find(id);
            if(row.Status == 0)
            {
                row.Status = 1;
            }
            else
            {
                row.Status = 0;
            }    
           
            db.Entry(row).State = EntityState.Modified;
            db.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/NhatKyNDController.cs
using MyDatabase;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.ClassCommon;

namespace WebAppMVC.Controllers
{
    public class NhatKyNDController : Controller
    {
        // GET: NhatKyND
        private MyDB db = new MyDB();
        // GET: Input
        [CustomAuthorizeAttribute(RoleID = "FrmNhatKyNguoiDung", QuyenXem = true)]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserList()
        {
            var congty_id = Convert.ToInt32(System.Web.HttpContext.Current.Session["congty_id"]);
            var userlist = db.UserCF.Where(m => m.UserID != "SysAdmin" && m.TenCongTy_ID == congty_id).ToList();
            return Json(userlist, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetListByDate(DateTime ngayStart, DateTime ngayEnd)
        {
            var congty_id = Convert.ToInt32(System.Web.HttpContext.Current.Session["congty_id"]);

            var list = (from p in db.DmNhatKyNDCF
                        where p.NgayGio >= ngayStart && p.NgayGio <= ngayEnd && p.NguoiDung_ID != "SysAdmin"
                        && p.TenCongTy_ID == congty_id
                        orderby p.NgayGio descending
                        select new
                        {
                            userId = p.NguoiDung_ID,
                            chucnang = p.ChucNang,
                            ngaygio = p.NgayGio,
                            thaotac = p.ThaoTac,
                            thamchieu = p.ThamChieu,
                            thamso = p.ThamSo,
                            sotien = p.SoTien

                        }).ToList();

            //return Json(list, JsonRequestBehavior.AllowGet);
            return Json(new { data = list }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult GetListByDateAndId(DateTime ngayStart, DateTime ngayEnd, string UserID)
        {
            var congty_id = Convert.ToInt32(System.Web.HttpContext.Current.Session["congty_id"]);
            var list = (from p in db.DmNhatKyNDCF
                        where p.NgayGio >= ngayStart
                        where p.NgayGio <= ngayEnd
                        where p.NguoiDung_ID == UserID && p.TenCongTy_ID == congty_id
                        orderby p.NgayGio descending
                        select new
                        {
                            userId = p.NguoiDung_ID,
                            chucnang = p.ChucNang,
                            ngaygio = p.NgayGio,
                            thaotac = p.ThaoTac,
                            thamchieu = p.ThamChieu,
                            thamso = p.ThamSo,
                            sotien = p.SoTien

                        }).ToList();

            //return Json(list, JsonRequestBehavior.AllowGet);
            return Json(new { data = list }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult DeleteDateAndUser(DateTime ngayStart, DateTime ngayEnd, String UserID)
        {
            var congty_id = Convert.ToInt32(System.Web.HttpContext.Current.Session["congty_id"]);
            //Delete 
            db.DmNhatKyNDCF.RemoveRange(db.DmNhatKyNDCF.Where(x => x.NgayGio >= ngayStart && x.NgayGio <= ngayEnd && x.NguoiDung_ID == UserID && x.TenCongTy_ID == congty_id));
            db.SaveChanges();

            return Json(true, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult DeleteDate(DateTime ngayStart, DateTime ngayEnd)
        {
            var congty_id = Convert.ToInt32(System.Web.HttpContext.Current.Session["congty_id"]);
            //Delete 
            db.DmNhatKyNDCF.RemoveRange(db.DmNhatKyNDCF.Where(x => x.NgayGio >= ngayStart && x.NgayGio <= ngayEnd && x.TenCongTy_ID == congty_id));
            db.SaveChanges();

            return Json(true, JsonRequestBehavior.AllowGet);

        }
    }
}

Views/Shared/No_Right.cshtml
@{
    ViewBag.Title = "Chưa phân quyền";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container card">
    <div class="card-body">
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Thông báo!</h5>
            Bạn không có quyền truy cập. Liên hệ với Admin!
        </div>
    </div>
</div>

Views/Shared/_Footer.cshtml
<footer class="main-footer">
    @*@using WebAppQLKhachHang.ClassCommon
    Tên công ty:<span class="text-danger"> @Html.RenderCompanyName()</span> -Tên csdl:<span class="text-danger"> @Html.RenderDataName()</span><br />*@
    <strong>Copyright &copy; 2020 <a href="https://thienphong.net" target="_blank">thienphong.net</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0.0
    </div>
</footer>

Views/Shared/_NavBar.cshtml
<!-- Left navbar links -->

<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="/Home/Index" class="nav-link"><i class="fas fa-home"></i> Home</a>
    </li>
   
</ul>

<!-- Right navbar links -->

<ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <a href="@Url.Action("Index", "QuanLyBan")" class="nav-link">
            <i class="fas fa-plus"></i>
        </a>
    </li>
    <!-- Dropdown User -->
    @if (ViewBag.name != "")
    {
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <i class="far fa-user"></i> @Html.Action("CallSessionUser", "Home")
                </a>
                <div class="dropdown-divider"></div>
                <a href="@Url.Action("logout", "Users")" class="dropdown-item">
                    <i class="fas fa-sign-out-alt"></i> Thoát
                </a>
            </div>
        </li>
    }
    <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
            <i class="fas fa-expand-arrows-alt"></i>
        </a>
    </li>
   
</ul>

Views/Shared/_SideBar.cshtml
<!-- Brand Logo -->
<a href="/Home/Index" class="brand-link">
    <img src="~/AdminLTE310/dist/img/logo128.png" alt="ThienPhong Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
    <span class="brand-text font-weight-light">Thiên Phong</span>
</a>
<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      
            <li class="nav-item">
                <a href="/Home/Index" class="nav-link">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        TỔNG QUAN
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Index","QuanLyBan")" class="nav-link">
                    <i class="nav-icon fas fa-barcode"></i>
                    <p>
                        BÁN HÀNG POS
                    </p>
                </a>
            </li>
            <!-- Ban hang -->
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        QUẢN LÝ BÀN
                        <i class="fas fa-angle-left right"></i>
                        <span class="badge badge-info right">4</span>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="@Url.Action("PhieuList","QuanLyBan")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Danh sách Phiếu xuất</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","QuanLyBan")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Quản lý bàn</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","PhieuThu")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Phiếu thu</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("PhieuOrderList","QuanLyBan")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Phiếu in order</p>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- Bao cao -->
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-chart-pie"></i>
                    <p>
                        BÁO CÁO
                        <i class="right fas fa-angle-left"></i>
                        <span class="badge badge-info right">6</span>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="@Url.Action("Index","BaoCaoDoanhThu")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Báo cáo doanh thu</p>
                        </a>
                    </li>
                </ul>
            </li>
            <!-- Danh muc -->
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-th">
                    </i>
                    <p>
                        DANH MỤC
                        <i class="fas fa-angle-left right"></i>
                        <span class="badge badge-info right">6</span>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="@Url.Action("Index","DmBan")" class="nav-link">
                            <i class="far fa-circle nav-icon">
                            </i>
                            <p>Danh mục Bàn</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","DmHangHoa")" class="nav-link">
                            <i class="far fa-circle nav-icon">
                            </i>
                            <p>Danh mục Hàng hóa</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","DmDoiTuong")" class="nav-link">
                            <i class="far fa-circle nav-icon">
                            </i>
                            <p>Danh mục đối tượng</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","DmLoaiThuChi")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Danh mục thu chi</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","DmNganHang")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Danh mục ngân hàng</p>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- He thong -->
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-cog"></i>
                    <p>
                        HỆ THỐNG
                        <i class="fas fa-angle-left right"></i>
                        <span class="badge badge-info right">5</span>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="@Url.Action("Index","QuanLyUsers")" class="nav-link">
                            <i class="fas fa-users nav-icon"></i>
                            <p>Quản lý người dùng</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","ChangePass")" class="nav-link">
                            <i class="fas fa-key nav-icon"></i>
                            <p>Đổi mật khẩu người dùng</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","NhatKyND")" class="nav-link">
                            <i class="fas fa-history nav-icon"></i>
                            <p>Xem nhật ký người dùng</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index","About")" class="nav-link">
                            <i class="fas fa-info nav-icon"></i>
                            <p>Thông tin bản quyền</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("LoginGiao","Users")" class="nav-link">
                            <i class="fas fa-users-cog nav-icon"></i>
                            <p>Update chương trình</p>
                        </a>
                    </li>
                </ul>
            </li>
            <!-- Trang thai -->
            <li class="nav-header">Trạng thái</li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="fas fa-user nav-icon"></i>
                    @using WebAppMVC.ClassCommon
                    @Html.RenderUserNameLogin()
                    @*@Html.Action("CallSessionFullname", "Home")*@
                </a>

            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("logout","Users")">
                    <i class="nav-icon far fa-circle text-danger"></i>Đăng xuất
                </a>
            </li>

        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div> 