Controllers/DangKyController.cs
using MyDatabase;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Management;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.ClassCommon;

namespace WebAppMVC.Controllers
{
    public class DangKyController : Controller
    {
        // GET: DangKy
        private MyDB db = new MyDB();
        #region Cong Ty Thien Phong
        private const int CREATE_NEW = 1;
        private const int OPEN_EXISTING = 3;
        private const uint GENERIC_READ = 0x80000000;
        private const uint GENERIC_WRITE = 0x40000000;
        private const int FILE_SHARE_READ = 0x1;
        private const int FILE_SHARE_WRITE = 0x2;
        private const int VER_PLATFORM_WIN32_NT = 2;
        private const int DFP_RECEIVE_DRIVE_DATA = 0x7C088;
        private const int INVALID_HANDLE_VALUE = -1;

        [StructLayout(LayoutKind.Sequential, Size = 8)]
        private class IDEREGS
        {
            public byte Features;
            public byte SectorCount;
            public byte SectorNumber;
            public byte CylinderLow;
            public byte CylinderHigh;
            public byte DriveHead;
            public byte Command;
            public byte Reserved;
        }

        [StructLayout(LayoutKind.Sequential, Size = 32)]
        private class SENDCMDINPARAMS
        {
            public int BufferSize;
            public IDEREGS DriveRegs;
            public byte DriveNumber;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public byte[] Reserved;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
            public int[] Reserved2;
            public SENDCMDINPARAMS()
            {
                DriveRegs = new IDEREGS();
                Reserved = new byte[3];
                Reserved2 = new int[4];
            }
        }
        [StructLayout(LayoutKind.Sequential, Size = 12)]
        private class DRIVERSTATUS
        {
            public byte DriveError;
            public byte IDEStatus;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public byte[] Reserved;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public int[] Reserved2;
            public DRIVERSTATUS()
            {
                Reserved = new byte[2];
                Reserved2 = new int[2];
            }
        }

        [StructLayout(LayoutKind.Sequential)]
        private class IDSECTOR
        {
            public short GenConfig;
            public short NumberCylinders;
            public short Reserved;
            public short NumberHeads;
            public short BytesPerTrack;
            public short BytesPerSector;
            public short SectorsPerTrack;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public short[] VendorUnique;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 20)]
            public char[] SerialNumber;
            public short BufferClass;
            public short BufferSize;
            public short ECCSize;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
            public char[] FirmwareRevision;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 40)]
            public char[] ModelNumber;
            public short MoreVendorUnique;
            public short DoubleWordIO;
            public short Capabilities;
            public short Reserved1;
            public short PIOTiming;
            public short DMATiming;
            public short BS;
            public short NumberCurrentCyls;
            public short NumberCurrentHeads;
            public short NumberCurrentSectorsPerTrack;
            public int CurrentSectorCapacity;
            public short MultipleSectorCapacity;
            public short MultipleSectorStuff;
            public int TotalAddressableSectors;
            public short SingleWordDMA;
            public short MultiWordDMA;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 382)]
            public byte[] Reserved2;
            public IDSECTOR()
            {
                VendorUnique = new short[3];
                Reserved2 = new byte[382];
                FirmwareRevision = new char[8];
                SerialNumber = new char[20];
                ModelNumber = new char[40];
            }
        }

        [StructLayout(LayoutKind.Sequential)]
        private class SENDCMDOUTPARAMS
        {
            public int BufferSize;
            public DRIVERSTATUS Status;
            public IDSECTOR IDS;
            public SENDCMDOUTPARAMS()
            {
                Status = new DRIVERSTATUS();
                IDS = new IDSECTOR();
            }
        }

        [System.Runtime.InteropServices.DllImport("kernel32.dll")]
        private static extern int CloseHandle(int hObject);

        [System.Runtime.InteropServices.DllImport("kernel32.dll")]
        private static extern int CreateFile(
                    string lpFileName,
                    uint dwDesiredAccess,
                    int dwShareMode,
                    int lpSecurityAttributes,
                    int dwCreationDisposition,
                    int dwFlagsAndAttributes,
                    int hTemplateFile
                );

        [System.Runtime.InteropServices.DllImport("kernel32.dll")]
        private static extern int DeviceIoControl(
                int hDevice,
                int dwIoControlCode,
                [In(), Out()] SENDCMDINPARAMS lpInBuffer,
                int lpInBufferSize,
                [In(), Out()] SENDCMDOUTPARAMS lpOutBuffer,
                int lpOutBufferSize,
                ref int lpBytesReturned,
                int lpOverlapped
            );

        private string SwapChars(char[] chars)
        {
            for (int i = 0; i <= chars.Length - 2; i += 2)
            {
                char t;
                t = chars[i];
                chars[i] = chars[i + 1];
                chars[i + 1] = t;
            }
            string s = new string(chars);
            return s;
        }

        #endregion

        public string masohdd = "";
        // GET: DangKy
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFiles()
        {
            bool isSuccess = false;
            string serverMessage = string.Empty;
            var fileOne = Request.Files[0] as HttpPostedFileBase;
            string uploadPath = ConfigurationManager.AppSettings["UPLOAD_PATH"].ToString();
            string newFileOne = Path.Combine(uploadPath, fileOne.FileName);

            fileOne.SaveAs(newFileOne);


            if (System.IO.File.Exists(newFileOne))
            {
                isSuccess = true;
                serverMessage = "Files have been uploaded successfully";
            }
            else
            {
                isSuccess = false;
                serverMessage = "Files upload is failed. Please try again.";
            }
            return Json(new { IsSucccess = isSuccess, ServerMessage = serverMessage }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSerial()
        {
            try
            {
                //var masohdd = "";
                string serialNumber = "";
                int handle, returnSize = 0;
                SENDCMDINPARAMS sci = new SENDCMDINPARAMS();
                SENDCMDOUTPARAMS sco = new SENDCMDOUTPARAMS();

                if (Environment.OSVersion.Platform == PlatformID.Win32NT)
                    //               \\.\PhysicalDrive0    Opens the first physical drive.
                    //               \\.\PhysicalDrive2    Opens the third physical drive.
                    // see more info on http://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx
                    handle = CreateFile("\\\\.\\PhysicalDrive" + "0", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE, 0, OPEN_EXISTING, 0, 0);
                else // for win'9x
                    handle = CreateFile("\\\\.\\Smartvsd", 0, 0, 0, CREATE_NEW, 0, 0);
                if (handle != INVALID_HANDLE_VALUE)
                {
                    sci.DriveRegs.Command = 0xEC;

                    if (DeviceIoControl(handle, DFP_RECEIVE_DRIVE_DATA, sci, Marshal.SizeOf(sci), sco, Marshal.SizeOf(sco), ref returnSize, 0) != 0)
                    {
                        serialNumber = SwapChars(sco.IDS.SerialNumber);
                    }
                    masohdd = ThienPhong.Encrypt(serialNumber.Trim(), "nhanbiet@041201101318@vethoi");
                    //masohdd = serialNumber.Trim();
                }
                else
                {
                    masohdd = ThienPhong.Encrypt(GetThienPhong().Trim(), "nhanbiet@041201101318@vethoi");
                    //masohdd = GetThienPhong().Trim();
                }
                return Json(masohdd, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        public string GetThienPhong()
        {

            //ArrayList hardDriveDetails = new ArrayList();
            string serialNumber = "";
            ManagementObjectSearcher moSearcher = new
            ManagementObjectSearcher("SELECT * FROM Win32_DiskDrive");

            foreach (ManagementObject wmi_HD in moSearcher.Get())
            {
                //HardDrive hd = new HardDrive();  // User Defined Class
                ////hd.Model = wmi_HD["Model"].ToString();  //Model Number
                ////hd.Type = wmi_HD["InterfaceType"].ToString();  //Interface Type
                //hd.SerialNo = wmi_HD["SerialNumber"].ToString(); //Serial Number
                //hardDriveDetails.Add(hd);
                //label1.Text = "Model : " + hd.Model;

Views/DangKy/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Đăng ký bản quyền sử dụng</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE310/plugins/fontawesome-free/css/all.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/AdminLTE310/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE310/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">

    <div class="login-box">
        <div class="login-logo">
            <a href="https://thienphong.net" target="_blank"><b>thienphong.net</b></a>
        </div>
        <div class="card">
            <div class="card-body">
                <p class="login-box-msg"><b>Thông tin tài khoản</b></p>
                <p>
                    Ngân hàng Ngoại thương – <b>VietCombank</b><br />
                    Chủ tài khoản: <b>Nguyễn Ngọc Phương Giao</b><br />
                    Số tài khoản: <b>0231 0001 55060</b>
                </p>
            </div>
        </div>

        <!-- Register  -->
        <div class="card">
            <div class="card-body">
                <p class="login-box-msg"><b>Đăng ký bản quyền</b></p>
                <div style="color:red;" id="uploadMsg"></div>
                <section id="RegisterForm">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <b>Mã số khách hàng : </b>
                        <div class="input-group mb-3">
                            <input type="text" id="txtMaKhachHang" name="txtMaKhachHang" class="form-control" placeholder="Full name">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-user"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">File bản quyền:</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="fileOne" name="fileOne">
                                    <label class="custom-file-label" for="exampleInputFile">Chọn file</label>
                                </div>
                                <span class="input-group-append">
                                    <button type="button" id="btn_save_file" class="btn btn-info btn-flat">Lưu file</button>
                                </span>
                            </div>
                        </div>
                        <div class="form-group" style="display:none;">
                            <input type="text" id="txtMaBanQuyen1" name="txtMaBanQuyen1" class="form-control" placeholder="Nhập mã bản quyền 1">
                            <input type="text" id="txtMaBanQuyen2" name="txtMaBanQuyen2" class="form-control" placeholder="Nhập mã bản quyền 2`">
                            <input type="text" id="txtMaBanQuyen3" name="txtMaBanQuyen3" class="form-control" placeholder="Nhập mã bản quyền 3">
                            <input type="text" id="txtMaBanQuyen4" name="txtMaBanQuyen4" class="form-control" placeholder="Nhập mã bản quyền 4">
                        </div>
                    }
                </section>

            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-6">
                        <button type="button" id="btn_dangky" name="btn_dangky" class="btn btn-warning btn-block">Đăng ký</button>
                    </div>
                    <div class="col-6">
                        <button type="button" id="btn_login" name="btn_login" class="btn btn-primary btn-block">Đăng nhập</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModalBanQuyen" role="dialog" data-url='@Url.Action("_BanQuyen","DangKy")'></div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/AdminLTE310/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE310/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE310/dist/js/adminlte.min.js"></script>
    <script src="~/AdminLTE310/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
</body>
</html>


<script type="text/javascript">

    $(document).ready(function () {
        $('#btn_save_file').click(function () {
            var file = $('#fileOne').get(0).files[0];
            if (file == null) {
                $('#uploadMsg').text('Bạn chưa chọn file bản quyền hoặc chọn lại file.');
                return;
            }

            var reader = new FileReader();
            reader.onload = function (e) {
                //get the file result, split by comma to remove the prefix, then base64 decode the contents
                var decodedText = atob(e.target.result.split(',')[1]);
                var allLines = decodedText.split('\n');
                $('#txtMaBanQuyen1').val(allLines[0]);
                $('#txtMaBanQuyen2').val(allLines[1]);
                $('#txtMaBanQuyen3').val(allLines[2]);
                $('#txtMaBanQuyen4').val(allLines[3]);
                //show the file contents
                //alert(decodedText);
            };
            reader.readAsDataURL(file);
            $('#uploadMsg').text('Bạn đã lưu file thành công tiếp theo nhấn vào đăng ký.');
        });

        $('#btn_dangky').click(function () {
            var ma01 = $('#txtMaBanQuyen1').val();
            var ma02 = $('#txtMaBanQuyen2').val();
            var ma03 = $('#txtMaBanQuyen3').val();
            var ma04 = $('#txtMaBanQuyen4').val();
            if (ma01 === "") {
                $('#uploadMsg').text('Chưa có file bản quyền hoặc chưa nhấn Lưu file.');
                return;
            }
            //Save
            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateDangKy", "DangKy")',
                data: {
                    Ma01: ma01,
                    Ma02: ma02,
                    Ma03: ma03,
                    Ma04: ma04
                },
                dataType: "json",
                success: function (response) {
                    $('#uploadMsg').text(response.ServerMessage);
                    Clearform();
                },
                error: function (data) {
                    $('#uploadMsg').text('Bạn chưa đăng ký được, liên hệ Mr Giao - 0913 423 525');
                }
            });
        });
        function Clearform() {
            $("#fileOne").val('');
            $('#txtMaBanQuyen1').val('');
            $('#txtMaBanQuyen2').val('');
            $('#txtMaBanQuyen3').val('');
            $('#txtMaBanQuyen4').val('');
        }
        $('#btn_login').click(function () {

            window.location.href = "/Users/Login";

        });
        $(function () {
            $.ajax({
                url: "/Users/GetMaKhachHang",
                type: "GET",
                dataType: "JSON",
                success: function (data) {
                    var s = data;
                    $('#txtMaKhachHang').val(s);
                },
            });
        });
        bsCustomFileInput.init();
    });
</script>

Views/DangKy/_BanQuyen.cshtml
<div class="container">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Thông tin bản quyền</h3>
                    <div class="card-tools">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                </div>
            </div>
            <form id="BanQuyen" name="BanQuyen" class="form-horizontal">
                <div class="modal-body">
                    <h3 class="text-center">Chương trình quản lý Bán hàng</h3>
                    <p>Sản phẩm được cấp bản quyền sử dụng cho:<br />Tên công ty: <span id="spTenCty"></span><br />Địa chỉ: <span id="spAddress"></span><br />Ngày cấp: <span id="spDateCap"></span> - Ngày hết hạn: <span id="spDateHetHan"></span></p>

                </div>
                <div class="card-footer">
                    <button type="submit" data-dismiss="modal" class="btn btn-default float-right">Đóng</button>
                </div>
            </form>
        </div>
    </div>
</div>